### ISSUE TITLE
[Bug][steelseries-gamesense] Mod crashes with 1.21.4

### ISSUE THREAD

**Issue by JayJay1989** [nevoka-be/Issues#20]
**Describe the bug**
If i update the fabric.mod.json with the new version minecraft does not even start (exit code 1)

**Logs**
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
     
Replace mod 'GameSenseMod' (gamesensemod) 1.15.1 with any version that is compatible with:
minecraft 1.21.4
More details:
     
Mod 'GameSenseMod' (gamesensemod) 1.15.1 requires version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.4!
  at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
  at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
  at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Reported by**: Luna (on Discord)
**Project**: steelseries-gamesense
**Mod Loader**: fabric

**Comment by JayJay1989** [comment]
#21 will fix this
